// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFyu2kzWhovP28Rt4rU9ZqAAzmwMZQdPw',
    appId: '1:544468135795:web:7f21fc69b8ec894e931f06',
    messagingSenderId: '544468135795',
    projectId: 'vehicheck-guide',
    authDomain: 'vehicheck-guide.firebaseapp.com',
    storageBucket: 'vehicheck-guide.firebasestorage.app',
    measurementId: 'G-DSSSFW0JFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtA12xOtB7oIC1FKzZs84dvRtfiIKb-Y',
    appId: '1:544468135795:android:a9c4a19902e2af75931f06',
    messagingSenderId: '544468135795',
    projectId: 'vehicheck-guide',
    storageBucket: 'vehicheck-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9cmL6UaqbEA3rChJ-_jm_Z6jpJjoqnPI',
    appId: '1:544468135795:ios:97a269ae2d3dab88931f06',
    messagingSenderId: '544468135795',
    projectId: 'vehicheck-guide',
    storageBucket: 'vehicheck-guide.firebasestorage.app',
    iosBundleId: 'com.example.vehicheckguide',
  );
}
